-- Add AI-generated summary cache column to spots
-- Populated lazily by spot-summary Edge Function on first SpotDetail open
-- Avoids repeat AI calls; can be regenerated by setting to NULL

ALTER TABLE public.spots ADD COLUMN IF NOT EXISTS ai_summary text;

-- Index for querying unsummarized spots (for batch backfill)
CREATE INDEX IF NOT EXISTS idx_spots_no_summary
  ON public.spots (id)
  WHERE ai_summary IS NULL AND is_flagged = false;
